name: .NET

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  Build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [
            GitHub
        ]
        solution: [
            src,
            sample/ReaLTaiizor.Defender,
            sample/ReaLTaiizor.Instagram,
            sample/ReaLTaiizor.Kaspersky,
            sample/ReaLTaiizor.Login,
            sample/ReaLTaiizor.Payment,
            sample/ReaLTaiizor.Player,
            sample/ReaLTaiizor.Rufus,
            sample/ReaLTaiizor.XAMPP,
            ready/ReaLTaiizor.AppLocker,
            ready/ReaLTaiizor.Stopwatch,
            ready/ReaLTaiizor.Translate,
            demo/ReaLTaiizor.UI,
            demo/ReaLTaiizor.UX
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101

    - name: Restore the ReaLTaiizor
      run: dotnet restore ${{ matrix.solution }} -p:Configuration=${{ matrix.configuration }}

    - name: Build the ReaLTaiizor
      run: dotnet build ${{ matrix.solution }} -c ${{ matrix.configuration }} --no-restore /nowarn:CS0067,CS0108,CS0109,CS0114,CS0169,CS0414,CS0649,CA1416,NU5104,NETSDK1138,SYSLIB0003

    - name: Test the ReaLTaiizor
      run: dotnet test ${{ matrix.solution }} -c ${{ matrix.configuration }} --no-build --verbosity normal